<?php
/**
 * AddTeam200Response
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  SeaTable\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Account Operations: System admin
 *
 * The official SeaTable API Reference (OpenAPI 3.0).
 *
 * The version of the OpenAPI document: 6.1
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SeaTable\Client\SysAdmin;

use \ArrayAccess;
use \SeaTable\Client\ObjectSerializer;

/**
 * AddTeam200Response Class Doc Comment
 *
 * @category Class
 * @package  SeaTable\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AddTeam200Response implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'addTeam_200_response';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'org_id' => 'int',
        'org_name' => 'string',
        'ctime' => 'string',
        'org_url_prefix' => 'string',
        'role' => 'string',
        'creator_email' => 'string',
        'creator_name' => 'string',
        'creator_contact_email' => 'string',
        'quota' => 'int',
        'storage_usage' => 'int',
        'storage_quota' => 'int',
        'max_user_number' => 'int',
        'rows_count' => 'int',
        'row_limit' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'org_id' => null,
        'org_name' => null,
        'ctime' => null,
        'org_url_prefix' => null,
        'role' => null,
        'creator_email' => null,
        'creator_name' => null,
        'creator_contact_email' => null,
        'quota' => null,
        'storage_usage' => null,
        'storage_quota' => null,
        'max_user_number' => null,
        'rows_count' => null,
        'row_limit' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'org_id' => false,
        'org_name' => false,
        'ctime' => false,
        'org_url_prefix' => false,
        'role' => false,
        'creator_email' => false,
        'creator_name' => false,
        'creator_contact_email' => false,
        'quota' => false,
        'storage_usage' => false,
        'storage_quota' => false,
        'max_user_number' => false,
        'rows_count' => false,
        'row_limit' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'org_id' => 'org_id',
        'org_name' => 'org_name',
        'ctime' => 'ctime',
        'org_url_prefix' => 'org_url_prefix',
        'role' => 'role',
        'creator_email' => 'creator_email',
        'creator_name' => 'creator_name',
        'creator_contact_email' => 'creator_contact_email',
        'quota' => 'quota',
        'storage_usage' => 'storage_usage',
        'storage_quota' => 'storage_quota',
        'max_user_number' => 'max_user_number',
        'rows_count' => 'rows_count',
        'row_limit' => 'row_limit'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'org_id' => 'setOrgId',
        'org_name' => 'setOrgName',
        'ctime' => 'setCtime',
        'org_url_prefix' => 'setOrgUrlPrefix',
        'role' => 'setRole',
        'creator_email' => 'setCreatorEmail',
        'creator_name' => 'setCreatorName',
        'creator_contact_email' => 'setCreatorContactEmail',
        'quota' => 'setQuota',
        'storage_usage' => 'setStorageUsage',
        'storage_quota' => 'setStorageQuota',
        'max_user_number' => 'setMaxUserNumber',
        'rows_count' => 'setRowsCount',
        'row_limit' => 'setRowLimit'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'org_id' => 'getOrgId',
        'org_name' => 'getOrgName',
        'ctime' => 'getCtime',
        'org_url_prefix' => 'getOrgUrlPrefix',
        'role' => 'getRole',
        'creator_email' => 'getCreatorEmail',
        'creator_name' => 'getCreatorName',
        'creator_contact_email' => 'getCreatorContactEmail',
        'quota' => 'getQuota',
        'storage_usage' => 'getStorageUsage',
        'storage_quota' => 'getStorageQuota',
        'max_user_number' => 'getMaxUserNumber',
        'rows_count' => 'getRowsCount',
        'row_limit' => 'getRowLimit'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('org_id', $data ?? [], null);
        $this->setIfExists('org_name', $data ?? [], null);
        $this->setIfExists('ctime', $data ?? [], null);
        $this->setIfExists('org_url_prefix', $data ?? [], null);
        $this->setIfExists('role', $data ?? [], null);
        $this->setIfExists('creator_email', $data ?? [], null);
        $this->setIfExists('creator_name', $data ?? [], null);
        $this->setIfExists('creator_contact_email', $data ?? [], null);
        $this->setIfExists('quota', $data ?? [], null);
        $this->setIfExists('storage_usage', $data ?? [], null);
        $this->setIfExists('storage_quota', $data ?? [], null);
        $this->setIfExists('max_user_number', $data ?? [], null);
        $this->setIfExists('rows_count', $data ?? [], null);
        $this->setIfExists('row_limit', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets org_id
     *
     * @return int|null
     */
    public function getOrgId()
    {
        return $this->container['org_id'];
    }

    /**
     * Sets org_id
     *
     * @param int|null $org_id org_id
     *
     * @return self
     */
    public function setOrgId($org_id)
    {
        if (is_null($org_id)) {
            throw new \InvalidArgumentException('non-nullable org_id cannot be null');
        }
        $this->container['org_id'] = $org_id;

        return $this;
    }

    /**
     * Gets org_name
     *
     * @return string|null
     */
    public function getOrgName()
    {
        return $this->container['org_name'];
    }

    /**
     * Sets org_name
     *
     * @param string|null $org_name org_name
     *
     * @return self
     */
    public function setOrgName($org_name)
    {
        if (is_null($org_name)) {
            throw new \InvalidArgumentException('non-nullable org_name cannot be null');
        }
        $this->container['org_name'] = $org_name;

        return $this;
    }

    /**
     * Gets ctime
     *
     * @return string|null
     */
    public function getCtime()
    {
        return $this->container['ctime'];
    }

    /**
     * Sets ctime
     *
     * @param string|null $ctime ctime
     *
     * @return self
     */
    public function setCtime($ctime)
    {
        if (is_null($ctime)) {
            throw new \InvalidArgumentException('non-nullable ctime cannot be null');
        }
        $this->container['ctime'] = $ctime;

        return $this;
    }

    /**
     * Gets org_url_prefix
     *
     * @return string|null
     */
    public function getOrgUrlPrefix()
    {
        return $this->container['org_url_prefix'];
    }

    /**
     * Sets org_url_prefix
     *
     * @param string|null $org_url_prefix org_url_prefix
     *
     * @return self
     */
    public function setOrgUrlPrefix($org_url_prefix)
    {
        if (is_null($org_url_prefix)) {
            throw new \InvalidArgumentException('non-nullable org_url_prefix cannot be null');
        }
        $this->container['org_url_prefix'] = $org_url_prefix;

        return $this;
    }

    /**
     * Gets role
     *
     * @return string|null
     */
    public function getRole()
    {
        return $this->container['role'];
    }

    /**
     * Sets role
     *
     * @param string|null $role role
     *
     * @return self
     */
    public function setRole($role)
    {
        if (is_null($role)) {
            throw new \InvalidArgumentException('non-nullable role cannot be null');
        }
        $this->container['role'] = $role;

        return $this;
    }

    /**
     * Gets creator_email
     *
     * @return string|null
     */
    public function getCreatorEmail()
    {
        return $this->container['creator_email'];
    }

    /**
     * Sets creator_email
     *
     * @param string|null $creator_email creator_email
     *
     * @return self
     */
    public function setCreatorEmail($creator_email)
    {
        if (is_null($creator_email)) {
            throw new \InvalidArgumentException('non-nullable creator_email cannot be null');
        }
        $this->container['creator_email'] = $creator_email;

        return $this;
    }

    /**
     * Gets creator_name
     *
     * @return string|null
     */
    public function getCreatorName()
    {
        return $this->container['creator_name'];
    }

    /**
     * Sets creator_name
     *
     * @param string|null $creator_name creator_name
     *
     * @return self
     */
    public function setCreatorName($creator_name)
    {
        if (is_null($creator_name)) {
            throw new \InvalidArgumentException('non-nullable creator_name cannot be null');
        }
        $this->container['creator_name'] = $creator_name;

        return $this;
    }

    /**
     * Gets creator_contact_email
     *
     * @return string|null
     */
    public function getCreatorContactEmail()
    {
        return $this->container['creator_contact_email'];
    }

    /**
     * Sets creator_contact_email
     *
     * @param string|null $creator_contact_email creator_contact_email
     *
     * @return self
     */
    public function setCreatorContactEmail($creator_contact_email)
    {
        if (is_null($creator_contact_email)) {
            throw new \InvalidArgumentException('non-nullable creator_contact_email cannot be null');
        }
        $this->container['creator_contact_email'] = $creator_contact_email;

        return $this;
    }

    /**
     * Gets quota
     *
     * @return int|null
     */
    public function getQuota()
    {
        return $this->container['quota'];
    }

    /**
     * Sets quota
     *
     * @param int|null $quota quota
     *
     * @return self
     */
    public function setQuota($quota)
    {
        if (is_null($quota)) {
            throw new \InvalidArgumentException('non-nullable quota cannot be null');
        }
        $this->container['quota'] = $quota;

        return $this;
    }

    /**
     * Gets storage_usage
     *
     * @return int|null
     */
    public function getStorageUsage()
    {
        return $this->container['storage_usage'];
    }

    /**
     * Sets storage_usage
     *
     * @param int|null $storage_usage storage_usage
     *
     * @return self
     */
    public function setStorageUsage($storage_usage)
    {
        if (is_null($storage_usage)) {
            throw new \InvalidArgumentException('non-nullable storage_usage cannot be null');
        }
        $this->container['storage_usage'] = $storage_usage;

        return $this;
    }

    /**
     * Gets storage_quota
     *
     * @return int|null
     */
    public function getStorageQuota()
    {
        return $this->container['storage_quota'];
    }

    /**
     * Sets storage_quota
     *
     * @param int|null $storage_quota storage_quota
     *
     * @return self
     */
    public function setStorageQuota($storage_quota)
    {
        if (is_null($storage_quota)) {
            throw new \InvalidArgumentException('non-nullable storage_quota cannot be null');
        }
        $this->container['storage_quota'] = $storage_quota;

        return $this;
    }

    /**
     * Gets max_user_number
     *
     * @return int|null
     */
    public function getMaxUserNumber()
    {
        return $this->container['max_user_number'];
    }

    /**
     * Sets max_user_number
     *
     * @param int|null $max_user_number max_user_number
     *
     * @return self
     */
    public function setMaxUserNumber($max_user_number)
    {
        if (is_null($max_user_number)) {
            throw new \InvalidArgumentException('non-nullable max_user_number cannot be null');
        }
        $this->container['max_user_number'] = $max_user_number;

        return $this;
    }

    /**
     * Gets rows_count
     *
     * @return int|null
     */
    public function getRowsCount()
    {
        return $this->container['rows_count'];
    }

    /**
     * Sets rows_count
     *
     * @param int|null $rows_count rows_count
     *
     * @return self
     */
    public function setRowsCount($rows_count)
    {
        if (is_null($rows_count)) {
            throw new \InvalidArgumentException('non-nullable rows_count cannot be null');
        }
        $this->container['rows_count'] = $rows_count;

        return $this;
    }

    /**
     * Gets row_limit
     *
     * @return int|null
     */
    public function getRowLimit()
    {
        return $this->container['row_limit'];
    }

    /**
     * Sets row_limit
     *
     * @param int|null $row_limit row_limit
     *
     * @return self
     */
    public function setRowLimit($row_limit)
    {
        if (is_null($row_limit)) {
            throw new \InvalidArgumentException('non-nullable row_limit cannot be null');
        }
        $this->container['row_limit'] = $row_limit;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


