site_name: SeaTable PHP API Manual
site_author: SeaTable
docs_dir: ./docs
site_url: https://seatable.github.io/seatable-api-php

repo_name: seatable/seatable-api-php
repo_url: https://github.com/seatable/seatable-api-php/
edit_uri: blob/main

copyright: Copyright &copy; 2020, 2022 SeaTable GmbH

theme:
  name: material
  custom_dir: theme
  # icon:
  logo: media/SeaTableElephant256-256.png
  favicon: media/seatable-elephant-favicon.ico
  palette:
    primary: white
    accent:

plugins:
  - search

# Customization
extra:
  social:
    - icon: 'seatable'
      name: 'SeaTable homepage'
      link: 'https://seatable.io/'
    - icon: 'simple/postman'
      name: 'SeaTable API Docs'
      link: 'https://api.seatable.io'
    - icon: 'fontawesome/solid/code'
      name: 'SeaTable Programming Manual'
      link: 'https://seatable.github.io/seatable-scripts/'
    - icon: 'material/progress-wrench'
      name: 'SeaTable Admin Manual'
      link: 'https://manual.seatable.io/'
    - icon: 'fontawesome/brands/docker'
      name: 'SeaTable on Docker Hub'
      link: 'https://hub.docker.com/u/seatable'
      separate: true
    - icon: 'logo'
      name: 'Made with Material for MkDocs + Mkdocs + Mike + GNU Make + <3'
      link: 'https://squidfunk.github.io/mkdocs-material/'
  version:
    provider: mike
    default: main

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
      toc_depth: "1-4"
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details

# Page tree
nav:
  - Overview: README.md
  - Upgrading: UPGRADING.md
  - Examples:
    - Add a new Column to a Base: doc/add-new-column-to-base.md
    - Get Content from a Base: doc/get-content-from-a-base.md
  - Topics:
    - doc/establish-the-connection.md
  - SeaTable API Docs: 'https://api.seatable.io'
  - SeaTable Homepage: 'https://seatable.io/'
