<?php
/**
 * LinkFormulaColumnLookupFormatTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SeaTable\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Base Operations (from 4.4)
 *
 * The official SeaTable API Reference (OpenAPI 3.0).
 *
 * The version of the OpenAPI document: 5.0
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SeaTable\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * LinkFormulaColumnLookupFormatTest Class Doc Comment
 *
 * @category    Class
 * @description Specify the link-formula column.
 * @package     SeaTable\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class LinkFormulaColumnLookupFormatTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LinkFormulaColumnLookupFormat"
     */
    public function testLinkFormulaColumnLookupFormat()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "formula"
     */
    public function testPropertyFormula()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "link_column"
     */
    public function testPropertyLinkColumn()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "level1_linked_column"
     */
    public function testPropertyLevel1LinkedColumn()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "level2_linked_column"
     */
    public function testPropertyLevel2LinkedColumn()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
