<?php
/**
 * ListGroupMembers200ResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  SeaTable\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Account Operations - Team admin
 *
 * The official SeaTable API Reference (OpenAPI 3.0).
 *
 * The version of the OpenAPI document: 6.1
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SeaTable\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ListGroupMembers200ResponseTest Class Doc Comment
 *
 * @category    Class
 * @description ListGroupMembers200Response
 * @package     SeaTable\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ListGroupMembers200ResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ListGroupMembers200Response"
     */
    public function testListGroupMembers200Response()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "group_id"
     */
    public function testPropertyGroupId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "group_name"
     */
    public function testPropertyGroupName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "members"
     */
    public function testPropertyMembers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
