<?php
/**
 * FormsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  SeaTable\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Account Operations: System admin
 *
 * The official SeaTable API Reference (OpenAPI 3.0).
 *
 * The version of the OpenAPI document: 4.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SeaTable\Client\Test\Api;

use \SeaTable\Client\Configuration;
use \SeaTable\Client\ApiException;
use \SeaTable\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FormsApiTest Class Doc Comment
 *
 * @category Class
 * @package  SeaTable\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FormsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteDataCollectionForms
     *
     * Delete Data Collection Forms.
     *
     */
    public function testDeleteDataCollectionForms()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteForm
     *
     * Delete Form.
     *
     */
    public function testDeleteForm()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listDataCollectionForms
     *
     * List Data Collection Forms.
     *
     */
    public function testListDataCollectionForms()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listForms
     *
     * List Forms.
     *
     */
    public function testListForms()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
