<?php
/**
 * LogsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  SeaTable\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Account Operations: System admin
 *
 * The official SeaTable API Reference (OpenAPI 3.0).
 *
 * The version of the OpenAPI document: 5.0
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SeaTable\Client\Test\Api;

use \SeaTable\Client\Configuration;
use \SeaTable\Client\ApiException;
use \SeaTable\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * LogsApiTest Class Doc Comment
 *
 * @category Class
 * @package  SeaTable\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LogsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for listAbuseReports
     *
     * List Abuse Reports.
     *
     */
    public function testListAbuseReports()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listEmailLogs
     *
     * List Email Logs.
     *
     */
    public function testListEmailLogs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listLoginLogs
     *
     * List Login Logs.
     *
     */
    public function testListLoginLogs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listRegistrationLogs
     *
     * List Registration Logs.
     *
     */
    public function testListRegistrationLogs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateAbuseReport
     *
     * Update Abuse Report.
     *
     */
    public function testUpdateAbuseReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
