name: check-backward-compatibility

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-backward-compatibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Roave BC Check
        uses: docker://nyholm/roave-bc-check-ga
