name: check-backward-compatibility

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  roave-bc-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  cp .config/$GITHUB_JOB.yaml .
      - name: Roave BC Check
        uses: docker://nyholm/roave-bc-check-ga
