name: 'GHP'

on:
  workflow_dispatch:
    paths: [ '.github/workflows/ghp-deploy.yml', '.config/mkdocs/**', 'doc/*.md', '*.md' ]
  pull_request:
    paths: [ '.github/workflows/ghp-deploy.yml', '.config/mkdocs/**', 'doc/*.md', '*.md' ]
    branches: [ 'main', 'next' ]
  push:
    paths: [ '.github/workflows/ghp-deploy.yml', '.config/mkdocs/**', 'doc/*.md', '*.md' ]
    branches: [ 'main', 'main-docs', 'next' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - working-directory: .config/mkdocs
        env:
          VIRTUAL_ENV: false
          MIKE_VERSION: 0.2
          MIKE_TITLE: 'main'
          SOURCE_DATE_EPOCH: 0
        run: |
          set -x
          pip install -r requirements.txt
          export -p | grep SOURCE_DATE_EPOCH
          make docs
          git config user.name ci-bot
          git config user.email ci-bot@example.com
          git fetch origin gh-pages:gh-pages
          mike deploy --title "$MIKE_VERSION ($MIKE_TITLE)" --push "$MIKE_VERSION"

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: 'docs-html-ghp'
          retention-days: 1
          path: |
            .config/mkdocs/site/**
